#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/mqttwol-sub

. /lib/functions/network.sh

append_iface() {
	local logical="$1"
	local dev

	if network_get_physdev dev "$logical" 2>/dev/null && [ -n "$dev" ]; then
		MQTTWOL_IFACES="${MQTTWOL_IFACES:+$MQTTWOL_IFACES }$dev"
	else
		MQTTWOL_IFACES="${MQTTWOL_IFACES:+$MQTTWOL_IFACES }$logical"
	fi
}

start_service() {
	config_load mqttwol

	local enabled server port use_auth username password topic

	config_get enabled main enabled 0
	[ "$enabled" = "1" ] || return 0

	config_get server main server
	config_get port main port 1883
	config_get use_auth main use_auth 0
	config_get username main username
	config_get password main password
	config_get topic main topic

	MQTTWOL_IFACES=""
	config_list_foreach main interface append_iface
	if [ -z "$MQTTWOL_IFACES" ]; then
		config_get legacy_if main interface "br-lan"
		for w in $legacy_if; do
			append_iface "$w"
		done
	fi

	[ -n "$server" ] || {
		logger -t mqttwol -p daemon.err "mqttwol: option server is empty"
		return 1
	}
	[ -n "$topic" ] || {
		logger -t mqttwol -p daemon.err "mqttwol: option topic is empty"
		return 1
	}
	[ -n "$MQTTWOL_IFACES" ] || {
		logger -t mqttwol -p daemon.err "mqttwol: no interface selected"
		return 1
	}

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param env MQTTWOL_SERVER="$server"
	procd_set_param env MQTTWOL_PORT="$port"
	if [ "$use_auth" = "1" ]; then
		procd_set_param env MQTTWOL_USERNAME="$username"
		procd_set_param env MQTTWOL_PASSWORD="$password"
	else
		procd_set_param env MQTTWOL_USERNAME=""
		procd_set_param env MQTTWOL_PASSWORD=""
	fi
	procd_set_param env MQTTWOL_TOPIC="$topic"
	procd_set_param env MQTTWOL_INTERFACES="$MQTTWOL_IFACES"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "mqttwol"
}

reload_service() {
	restart
}
