#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/mqttwol-sub

start_service() {
	config_load mqttwol

	local enabled server port username password topic interface

	config_get enabled main enabled 0
	[ "$enabled" = "1" ] || return 0

	config_get server main server
	config_get port main port 1883
	config_get username main username
	config_get password main password
	config_get topic main topic
	config_get interface main interface "br-lan"

	[ -n "$server" ] || {
		logger -t mqttwol -p daemon.err "mqttwol: option server is empty"
		return 1
	}
	[ -n "$topic" ] || {
		logger -t mqttwol -p daemon.err "mqttwol: option topic is empty"
		return 1
	}
	[ -n "$interface" ] || {
		logger -t mqttwol -p daemon.err "mqttwol: option interface is empty"
		return 1
	}

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param env MQTTWOL_SERVER="$server"
	procd_set_param env MQTTWOL_PORT="$port"
	procd_set_param env MQTTWOL_USERNAME="$username"
	procd_set_param env MQTTWOL_PASSWORD="$password"
	procd_set_param env MQTTWOL_TOPIC="$topic"
	procd_set_param env MQTTWOL_INTERFACE="$interface"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "mqttwol"
}

reload_service() {
	restart
}
